"""Add username and temp_password_hash to OTP table

Revision ID: ddd7121f9186
Revises: 71a2461959a7
Create Date: 2025-06-10 12:17:03.113431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd7121f9186'
down_revision = '71a2461959a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('temp_password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('temp_password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
